service: virtual-cd-rack # make sure to update this

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  environment:
    SERVICE_NAME: ${self:service}
    DYNAMODB_TABLE: ${self:service}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  # Get methods
  ping:
    events:
      - http:
          method: get
          path: ping
          cors: true
    handler: api/index.ping

  search:
    events:
      - http:
          method: post
          path: search
          cors: true
    handler: api/index.searchBarcode

  add:
    events:
      - http:
          method: post
          path: add
          cors: true
    handler: api/index.addRelease

  # scheduledEvents:
  #   events:
  #     - schedule: rate(1 minute)
  #   handler: api/index.schedule

resources:
  Resources:
    MainTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: barcode
            AttributeType: S
          -
            AttributeName: title
            AttributeType: S
        KeySchema:
          -
            AttributeName: barcode
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: TitleIndex
            KeySchema:
              - AttributeName: title
                KeyType: HASH
            Projection:
              ProjectionType: 'ALL'
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-include-dependencies
  - serverless-prune-plugin

package:
  excludeDevDependencies: false
  exclude:
    - static/**
    - store/**
    - middleware/**
    - layouts/**
    - components/**
    - assets/**
    - api-local/**
    - plugins/**
    - pages/**
    - dist/**
    - tools/**
    - .nuxt/**

custom:
  prune:
    automatic: true
    number: 3
